train_model:
  XGBRegressor:
    learning_rate:
    - 0.06
    max_depth:
    - 6
    n_estimators:
    - 200
    subsample:
    - 0.5
  CatBoostRegressor:
    boosting_type:
    - Ordered
    depth:
    - 3
    l2_leaf_reg:
    - 2
    learning_rate:
    - 0.03
base_model_score: '0.9847679789100191'
